; configs/colloid_kumar.ini
;
; Mpemba effect in a colloid (Kumar & Bechhoefer, Nature 2020).
; Overdamped Langevin in an asymmetric double-well potential.

[ensemble]
n_trajectories = 500000
seed           = 195935983

#Values from normalization, go to README on Langevin.
[quench]
T_hot  = 1.33141872      ; hot initial temperature 
T_warm = 1.114876508         ; warm initial (cooler than hot, but the slower-relaxer)
T_bath = 1.0          ; bath temperature (also equilibrium temperature)

[potential]
U0   = 8.0    #initial 6.0 well depth scale
h    = 1.5  #1.5 o 1.2 Initial 0.8            ; tilt asymmetry
L    = 1.0
xmin = -3.0
xmax = 3.0

[integration]
t_max           = 1.0  #max 0.5
dt              = 5e-5
n_bins          = 200
n_steps_per_log = 50

[io]
output_dir = results/langevin
